### ISSUE TITLE
Feature Request: co-op with netplay?

### ISSUE THREAD

**Issue by Tippek** [HelloFangaming/HelloMarioEngine#12]
I think it will great if I could play with friend over internet. New character: Luigi - just recolored Mario's sprites. I added Luigi in 6.0.2 version, but I absolutely dont know how to add netplay. So if its possible then no matter how it will realized. Split Screen or individual screen for each. Both variants will good.

**Comment by HelloFangaming** [comment]
Sorry, but this is not something I plan on adding...
