### ISSUE TITLE
Classic Bowser audio problem

### ISSUE THREAD

**Issue by XDavidXtreme** [HelloFangaming/HelloMarioEngine#13]
I don't know if this happens only to me or to other but when I defeat Classic Bowser the music may not stop and continue playing. It is playing when I am in another level or when I am in the World Map. So I hope a fix will come fast.

**Comment by HelloFangaming** [comment]
Works fine for me. Make sure to double check any code changes you made to the engine.

**Comment by HelloFangaming** [comment]
Unable to reproduce...

**Comment by XDavidXtreme** [comment]
I Didn't Touch The Codes I Just Played The Preview To See How It Is!
