### ISSUE TITLE
Sliding under blocks while big breaks them

### ISSUE THREAD

**Issue by ZwipZwapZapony** [HelloFangaming/HelloMarioEngine#15]
While messing around with a gamepad fix I made, I noticed blocks break when sliding under them. Naturally, that's a thing that can easily happen in normal gameplay, and as such is a somewhat major bug, so I went ahead and [recorded it](https://youtu.be/QPqyhH_eE78) for you to see the issue as it is. I promise, I did not mess with any code at all besides fixing gamepad support.

**Comment by HelloFangaming** [comment]
Fixed...
