### ISSUE TITLE
World Map

### ISSUE THREAD

**Issue by Flaregeno** [HelloFangaming/HelloMarioEngine#17]
Today, i think i have found a bug. I am trying to create a custom world map and i place Mario and the start object where I want them. When i run the game though, Mario spawns way off of the start object. He even proceeds to do this with every new map i make. Is there somehow a solution to this "bug"?
Also, i would like to restart files

**Comment by HelloFangaming** [comment]
Mario's location is being loaded from your last save file. By default, GM: Studio saves these files to %localappdata\Game_Name.
