### ISSUE TITLE
Not really a issue... but i need help on this

### ISSUE THREAD

**Issue by Wiiucoop** [HelloFangaming/HelloMarioEngine#18]
Im trying to add walljumpshroom physics to mario instead of using the powerup make it happen...

but the problem is.... how i do that? (since i dont want to make any mistakes editing objects...)

can you help me?

**Comment by HelloFangaming** [comment]
In obj_mario's User Defined 2 event, search for "//Handles checking whether Mario can wall climb or wall jump", and remove the global.powerup checks from the if statement directly below.

In obj_mario's User Defined 5 event, search for "//If Mario does not have the appropriate powerup", and remove that first line from the if statement directly below.

Also, make sure Frog Mario has a skid sprite.

**Comment by Wiiucoop** [comment]
Thanks ALOT!!! but... do you know where do i download luigi sprites in gmx format? or i need to download regular png and import them one by one into mario sprites?
