### ISSUE TITLE
Xbox 360 Controller - Works then Fails

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [HelloFangaming/HelloMarioEngine#19]
Okay so let me start by saying thank you so much for making this. All gratefulness aside the controller worked for about 20 secs then Mario started auto bouncing after a few more seconds and hitting everything I could it worked again. After about 10 secs of working it failed again at this point I get pissed and quit.

**Comment by HelloFangaming** [comment]
Should be fine in v6.1.6.
