### ISSUE TITLE
Broken Gamepad controls

### ISSUE THREAD

**Issue by HenrikoMagnifico** [HelloFangaming/HelloMarioEngine#21]
I have found an issue with the game pad controls in Hello Mario Engine (the latest release). It appears that, when using a game pad, Mario won't jump correctly all the time. Specifically, sometimes he will jump really short even though I've long pressed the button, and sometimes he won't even jump at all. He also sporadically jumps about even when I'm not pressing the jump button at random, which becomes very annoying when you're trying to complete tight platforming sections. 

I would love for this to get fixed ASAP! 👍

**Comment by chad78** [comment]
Hi,

I'm not a programmer, and I don't have any way to fix this issue - but I expect it would be helpful for the people who could fix this to know the following:

What type of gamepad are you using?  What Brand, what model?  Is it wired or wireless?  Have you tried other gamepads?  If so - does the problem show up again with all the gamepads you've used, or just certain one(s)?  What operating system are you using?  (Windows?  10?  64-bit?  Home?)

I've filled out enough bug reports to know that this type of information can help them replicate the problem, which is the first step to fixing it.

Good luck!

**Comment by HenrikoMagnifico** [comment]
Thanks for the reply @chad78 ! Here is some more info on the matter.

Type of gamepad: Xbox 360 Wired Controller

Operating system: Windows 10 64-bit Professional

I have not tried any other types of gamepads because I only own this one & a second controller of the same type (Xbox 360 wired). I have this problem with both of them and neither of them show up as "faulty" when doing the Windows gamepad responsivity test.

**Comment by HelloFangaming** [comment]
The fix: 6dcc8a65f7e077c1eda588b7875c8cd2570b0b31
This fixed the problem on my Xbox controller, and I'm not entirely sure why, so let me know if this fixes the problem for you.

**Comment by HenrikoMagnifico** [comment]
Yup that fixed the problem. Thanks!
