### ISSUE TITLE
Analog stick does not act as the D-pad on a gamepad controller

### ISSUE THREAD

**Issue by HenrikoMagnifico** [HelloFangaming/HelloMarioEngine#22]
Hello! I've encountered a small inconvenience with the Hello Mario Engine. As it seems, it is not possible to use the left or right analog stick to control Mario - it only works with the D-pad. Unfortunately, the D-pad is awful on the Xbox 360 controller and it makes it really uncomfortable to play the game that way. Is Analog stick support something that is coming soon? It would be very much appreciated.

-Henriko

**Comment by HelloFangaming** [comment]
All done: 4ec15a2075eee936d88fa0daebf7dc586d9d1185
If you copy the code from here, know that < and > appear differently when viewing the code outside of GameMaker.

**Comment by HenrikoMagnifico** [comment]
@HelloFangaming Awesome. Thanks!
