### ISSUE TITLE
[SOLUTION] Walk sprite bug

### ISSUE THREAD

**Issue by DanielIDK** [HelloFangaming/HelloMarioEngine#23]
If you tap the right arrow key just for a short time Mario will just slide over the ground for a few pixels without changing his sprite to the walking animation. If you press left very shortly this does not happen and he instantly changes his sprite. Can you post a small fix for this issue, because im not able to identify what causes the issue.

**Comment by DanielIDK** [comment]
I just fixed it:

Im obj_mario End Step event
`
96     image_speed = (abs(hspeed)*-1)/10
`

**Comment by HelloFangaming** [comment]
I added your fix, with some changes: ec8b1dd96c4f002d6b64ae6fff0fdf12d72ea22b

**Comment by DanielIDK** [comment]
I don't know if you will read this, but in the level manager object where you are drawing the HUD you made a small mistake, I think so at least, because you are drawing the text for the amount of lives remaining with string_format, but I think you meant to use string_fill_zeros(lives, 2). It just stood out to me, because it was the only string on the HUD which wasn't filled with zeros.
