### ISSUE TITLE
Block collision

### ISSUE THREAD

**Issue by DanielIDK** [HelloFangaming/HelloMarioEngine#24]
If you have a high enough hspeed and the correct angle it is possible to hit a block/brick by falling into the trigger from the side. To fix this you can add the following to the "obj_blockparent" Step event under line 4

```
and obj_mario.vspeed <= 0
```

This will make the event check if Mario is moving up or if he has already stopped because of collision. It will not return true if Mario falls and fix the issue that way. Alternatively you could also check with "and not".

```
and !obj_mario.vspeed > 0
```

**Comment by HelloFangaming** [comment]
Fixed in v6.2.1
