### ISSUE TITLE
Multiple

### ISSUE THREAD

**Issue by Yoshubs** [HelloFangaming/HelloMarioEngine#28]
I'll just be listing them off:
-Sluggish movement
-Robotic/control free actions
-Confusing physics
-Lack of jumping while sliding down slopes
-Ear busting noises

These should be fixed before you decide to pull a Powerup update.

**Comment by chad78** [comment]
Those aren't bugs.  Many of those are personal preference, and most are vague at best.

What's confusing about the physics?  Sluggish movement compared to what?  What movement is sluggish?   What actions are "Control free" - what does that even mean?

The only thing on that list that is even close to being a bug is "Lack of jumping while sliding down slopes".

"Ear busting noises" doesn't explain anything.  If you are talking about the unmuteble player character voiceovers - I would like the option to turn them off, or to at least lower the volume and/or frequency (like the Bubsy 3 slider).

**Comment by Yoshubs** [comment]
Sluggish compared to other mario engines/games, "control free" as in fixed actions with lack of acceleration (the cloud spin as an example). Not only the voiceovers but the songs and sounds. I think those need a revamp.
