### ISSUE TITLE
GamePad support not working on PSVita Console

### ISSUE THREAD

**Issue by KuromeSan** [HelloFangaming/HelloMarioEngine#31]
The up/down/left/right and D-PAD Buttons work no problem. i can choose between file A/B/C 
however when i go to press gp_face1 (mapped to X button on console) it doesn't do anything infact none of them do :?

another thing is that it immediately crashes unless your using YYC

**Comment by KuromeSan** [comment]
Ah, okay i found the issue to be with obj_persistent

it seems the console does not like using 
```
    //Make the x key do everything the shift key does
    keyboard_set_map(ord('X'),vk_shift)
    
    //Make the z key do everything the control key does
    keyboard_set_map(ord('Z'),vk_control)
```

and then trying to press those keys like this

```
    //X button
    if gamepad_button_check_pressed(0,gp_face3)
        keyboard_key_press(ord('Z'))
    else if gamepad_button_check_released(0,gp_face3)
        keyboard_key_release(ord('Z'))

    //A button
    if gamepad_button_check_pressed(0,gp_face1)
        keyboard_key_press(ord('X'))
    else if gamepad_button_check_released(0,gp_face1)
        keyboard_key_release(ord('X'))
```

this seems to confuse it, 

why not make it press vk_start and vk_control directly instead of X/Z ? this fixes that issue for me

**Comment by HelloFangaming** [comment]
Using those keys directly causes issues on Windows for some reason. If this is just Vita, then I'll leave it as is.
