### ISSUE TITLE
Speed is too fast

### ISSUE THREAD

**Issue by KeymilAnimations** [HelloFangaming/HelloMarioEngine#36]
I have a problem with the speed.
I use gms 1.4.9999 and whenever i open the game the fps is way too high and unplayable.
any clue why this happens or how to fix it?

**Comment by HelloFangaming** [comment]
Unfortunately, this is a bug with GameMaker: Studio 1.4. To fix this, you need to open Options.ini in Notepad, and change AlternateSyncMethod to 0 if the game is too fast, or 1 if the game is too slow. If this does not fix your problem, then you can also try using the [GM:S Scheduler Fix](https://github.com/omicronrex/gms_scheduler_fix).

**Comment by YounesSamatta** [comment]
[GM:S Scheduler Fix](https://github.com/omicronrex/gms_scheduler_fix) worked for me only after changing AlternateSyncMethod to 0
